### ISSUE TITLE
Possible to see reason for kubelet being unable to launch a pod?

### ISSUE THREAD

**Issue by aknuds1** [coreos/kubernetes#11]
Is there a way to see why [kubelet.service](https://coreos.com/kubernetes/docs/latest/deploy-master.html#create-the-kubelet-unit) failed to launch a pod? Currently I have to run pods manually via `docker run` in order to see the reason for failures.

**Comment by aknuds1** [comment]
I've found I can find corresponding container logs in /var/log/containers/kube-apiserver-*.

**Comment by robszumski** [comment]
Chatted with @aknuds1 on Slack. The journal on the kubelet is working just fine, it's just not outputting helpful debug information.

Pointed towards `docker ps -a`/`docker logs` and turning up the verbosity on the kubelet.

**Comment by aknuds1** [comment]
I don't agree that the issue should be closed, as the reason for the pod failure should definitely be in the journal. It's not very helpful for the journal not to say why the pod is failing, as it leaves the user clueless as to what to do.

**Comment by aknuds1** [comment]
However, do you mean that this is an issue for the upstream repo @robszumski? If there isn't already an issue there, I should create it.

**Comment by robszumski** [comment]
@aknuds1 Yes, do a quick search on https://github.com/kubernetes/kubernetes/issues and open one if you don't see an existing issue.

Additionally, I created https://github.com/coreos/coreos-kubernetes/issues/294 to see if we want to increase the verbosity by default.

**Comment by aknuds1** [comment]
@robszumski I created [an issue](https://github.com/kubernetes/kubernetes/issues/22151) already.
