### ISSUE TITLE
hyperkube: Upgrade ceph-common to Jewel LTS

### ISSUE THREAD

**Issue by bzub** [coreos/kubernetes#120]
ceph-common clients (ceph, rbd, etc) are at v0.80.7 Firefly, released in 2014 and "retired" last year.

Jewel  is the latest LTS released last year, and I'd guess is the most common version of Ceph deployed right now.  When I upgrade ceph-common to Jewel I seem to have much fewer hangups with RBD PersistentVolumes (none actually).

PR incoming to update Dockerfile.  Thanks.

http://docs.ceph.com/docs/master/releases/

**Comment by bzub** [comment]
Well I'm not sure if there's a branch I should submit a PR against, the change is simple:

`kubernetes/cluster/images/hyperkube/Dockerfile`

before:
```Dockerfile
# [...]
RUN DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get -yy -q install \
    iptables \
    # [...]
```

after:
```Dockerfile
# [...]
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 08b73419ac32b4e966c1a330e84ac2c0460f3994 \
    && echo "deb http://download.ceph.com/debian-jewel/ jessie main" > /etc/apt/sources.list.d/ceph-jewel.list \
    && DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get -yy -q install \
    iptables \
    # [...]
```

**Comment by saurfangg** [comment]
Any plans to integrate this fix? We're hitting this issue right now and have to manually update the version running in the container.

**Comment by squat** [comment]
@saurfangg @bzub we no longer carry a patch to add ceph-common to the hyperkube image since it ships in upstream kubernetes since 1.8.x. [0]. If you are still experiencing this issue I suggest opening it upstream since we would prefer not to start shipping different versions of these packages.

[0] https://github.com/kubernetes/kubernetes/blob/master/build/debian-hyperkube-base/Dockerfile#L35

**Comment by bzub** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/45010
