### ISSUE TITLE
HyperKube v1.7.8_coreos.1 reporting v1.7.8+coreos.0

### ISSUE THREAD

**Issue by Vrtak-CZ** [coreos/kubernetes#173]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
```
kubectl get nodes
NAME                                           STATUS    ROLES     AGE       VERSION
ip-10-101-111-62.eu-west-1.compute.internal    Ready     <none>    1m        v1.7.8+coreos.0
ip-10-101-112-124.eu-west-1.compute.internal   Ready     <none>    2m        v1.7.8+coreos.0
ip-10-101-122-254.eu-west-1.compute.internal   Ready     master    8m        v1.7.8+coreos.0
ip-10-101-123-204.eu-west-1.compute.internal   Ready     master    8m        v1.7.8+coreos.0
```

**What you expected to happen**:
```
kubectl get nodes
NAME                                           STATUS    ROLES     AGE       VERSION
ip-10-101-111-62.eu-west-1.compute.internal    Ready     <none>    1m        v1.7.8+coreos.1
ip-10-101-112-124.eu-west-1.compute.internal   Ready     <none>    2m        v1.7.8+coreos.1
ip-10-101-122-254.eu-west-1.compute.internal   Ready     master    8m        v1.7.8+coreos.1
ip-10-101-123-204.eu-west-1.compute.internal   Ready     master    8m        v1.7.8+coreos.1
```

**How to reproduce it (as minimally and precisely as possible)**:

use hyperkube image `v1.7.8_coreos.1`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration**: `v1.7.8_coreos.1` - `quay.io/coreos/hyperkube@sha256:80daee0be2174f9f71e70579868f10b92e784f352e72687ab67c8c399538f2b3`
- OS (e.g. from /etc/os-release): `Container Linux by CoreOS - 1520.6.0`
- Kernel (e.g. `uname -a`): `Linux ip-10-101-112-124.eu-west-1.compute.internal 4.13.5-coreos-r2 #1 SMP Thu Oct 12 03:21:09 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux`

**Comment by squat** [comment]
Thanks @Vrtak-CZ. This failure was introduced while hastily cutting 1.7.8+coreos.1. 1.7.8+coreos.1 and 1.7.8+coreos.0 intentionally point at the same commit but should report different tags. coreos.2 is being built right now to point at the same revision but correctly report the version as 1.7.8+coreos.2.

**Comment by squat** [comment]
1.7.8+coreos.2 is out and behaves as expected. Thanks again for raising this issue, @Vrtak-CZ. Please note that this issue only affects the version reported by the Kubelet while the binaries are otherwise correctly built.
