### ISSUE TITLE
configmap with springboot application.properties

### ISSUE THREAD

**Issue by hppx5456** [coreos/kubernetes#220]
**What happened**:
I want to mount the configuration file in the springboot with configmap to achieve the application auto heel when modifying the configmap, but now you don't use the configuration data in the configmap when you start the project

**Anything else we need to know?**:
this is my deployment.yaml
![image](https://user-images.githubusercontent.com/26714352/40340656-b8a740c4-5db2-11e8-9197-a578aa69623e.png)

this is configmap
![image](https://user-images.githubusercontent.com/26714352/40340719-47c48e9c-5db3-11e8-9f5e-366d3f39486d.png)

when i use kubectl exec -it springboot-mychart-78657856c7-cjsv7 /bin/bash
i see Configmap has been mounted in the container
![image](https://user-images.githubusercontent.com/26714352/40340822-df124622-5db3-11e8-9c5f-180f01fd9589.png)

But when I looked at docker logs, I found that the port that the container started was 8080, not the 8999 I set in configmap.

![image](https://user-images.githubusercontent.com/26714352/40340989-036e071c-5db5-11e8-8810-6b41a6b7eafd.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ericchiang** [comment]
Hi this is not a kubernetes or springboot issue tracker. It's a tracker for CoreOS kubernetes release artifacts. Please open an issue with whatever repo you got your manisfests from.
