### ISSUE TITLE
v1.10.4 not published to Quay.

### ISSUE THREAD

**Issue by JTarasovic** [coreos/kubernetes#221]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
kubernetes 1.10.4 was released on June 2.

**What you expected to happen**:
`v1.10.4_coreos.0` would be published to quay.io

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by sfudeus** [comment]
Same with 1.10.5. from June 21 and 1.11.0 from this week. Are there any plans not to maintain the images anymore?

**Comment by george-angel** [comment]
Thats right, https://groups.google.com/forum/#!topic/coreos-user/rzsSxYRZxOI

**Comment by JTarasovic** [comment]
Yeah, this could probably use clarification.

> We are continuing support for our Hyperkube image for Kubernetes 1.8, 1.9, and
1.10. We will not be deleting old images, and will be continuing to build new
images based on point releases, but don't plan on releasing images for the 1.11
series.

A CoreOS blog post would probably be a valuable reminder to the wider community that this is happening.

Otherwise, I'll go ahead and close. I appreciate everyone's help getting to the bottom of this.

**Comment by rphillips** [comment]
I kicked the builds on these images off... They should appear on quay today.

**Comment by rphillips** [comment]
1.8.14_coreos.0, 1.10.4_coreos.0, 1.10.5_coreos.0 pushed to quay
