### ISSUE TITLE
hyperkube missing conntrack binary

### ISSUE THREAD

**Issue by sgrimee** [coreos/kubernetes#42]
We see a lot of the error below in the logs of the kube-proxy container: 

```
E0610 15:55:24.811934       1 proxier.go:603] conntrack return with error: Error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
```

The 'conntrack' executable does not seem to be in the hyperkube image (quay.io/coreos/hyperkube:v1.2.4_coreos.1), nor is it mounted or even present on the host (CoreOS stable 1010.5.0)

This binary [seems to be needed](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L594) to clean-up UDP 'sessions' when a pod/endpoint is removed.

Indeed, we see catastrophic recovery times when killing one of several kube-dns pods, client pods making repeated lookups take a long time to recover, often causing applications to crash. We suspect queries are still forwarded to the deleted pod because iptables was not correctly cleaned up.
For the record, we are now running dnsmasq in rkt on all nodes and using it as a nameserver for all pods, it directs cluster queries to the kube-dns service and other queries directly to upstream dns servers. This completely masks the DNS problem for us, but this issue can cause problems for other udp applications.

**Comment by peebs** [comment]
It indeed is not in CoreOS so it must be in the hyperkube image. It looks like upstream has begun including the conntrack binary in the hyperkube image. See: https://github.com/kubernetes/kubernetes/pull/26839

So if you upgrade to any v1.3.x image this should resolve your problem. Is it possible for you to upgrade in the meantime?

**Comment by sgrimee** [comment]
Yes we have just upgraded. Thank you!
